title: 시니카미
email: ikocos.au@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: /daily
url: sinikami.github.io
twitter_username: lovejie2002
github_username: sinikami
markdown: kramdown
theme: jekyll-theme-minimal #minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

bootstrap:
  assets: true

category_dir: category/
tag_dir: tag/
