title: 시니카미
email: ikocos.au@gmail.com
description: ''
baseurl: /daily
url: 'http://sinikami.github.io'
twitter_username: lovejie2002
github_username: sinikami
theme: jekyll-theme-minimal  #minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-seo-tag
repository: sinikami/sinikami.github.io
